### ISSUE TITLE
Update to WordPress 5.4.2

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/wordpress-network#15]
Hi folks!

5.4.2 was rolled out few days ago. When would be the upstream updates will be rolled out for WP Multisites? 

Thanks!

**Comment by CdrMarks** [comment]
@carl-alberto I know this issue is very old, but I did want to reply that I see version 5.4.2 was tagged on June 10, 2022.
https://github.com/pantheon-systems/wordpress-network/releases/tag/5.4.2

**Comment by carl-alberto** [comment]
Awesome thanks haha!
