### ISSUE TITLE
Update to WordPress 4.4.1

### ISSUE THREAD

**Issue by bmackinney** [pantheon-systems/wordpress-network#2]
@greg-1-anderson

**Comment by greg-1-anderson** [comment]
I don't seem to have access to write to this repository atm.

I looked into it, and this repository matches exactly, same commit hashes and everything, with [pantheon-systems/WordPress](https://github.com/pantheon-systems/WordPress).

I brought these back in sync via:
```
git checkout -b wp44
git remote add pantheon-WordPress git@github.com:pantheon-systems/WordPress.git
git pull pantheon-WordPress master
git push origin wp44
```
That last one failed, though. :)

Seems we don't need this repository at all; perhaps it is here to hold planned future changes.

**Comment by bmackinney** [comment]
@greg-1-anderson This repository is necessary because if two products use the same repository, all sites from both products will display one upstream in the dashboard. For a while all WordPress sites showed "WordPress Site Network". @joshkoenig @greg-1-anderson needs write access to this repo. 

@greg-1-anderson I updated the title to the security release.

**Comment by ari-gold** [comment]
Hey @greg-1-anderson. You should now have write access
