### ISSUE TITLE
Clean up unused / deprecated branches

### ISSUE THREAD

**Issue by kyletaylored** [pantheon-systems/wordpress-network#40]
When creating a new site from this upstream (and the standard WP upstream), all git branches are cloned into the Pantheon site repository, making a bit of a mess in the multidev overview.

Either the branches need to regularly be pruned in the upstream, or we need to ignore branches on site creation. Thoughts?

![image](https://user-images.githubusercontent.com/1759794/132933970-2eb5e89e-c50c-4d7f-ba2a-88c5a109585b.png)

**Comment by jazzsequence** [comment]
Branches have been pruned (not sure when the work was actually done, but as of today, the 3rd of March in the year 2023, there was only one extraneous branch from a PR which I deleted).
