### ISSUE TITLE
CircleCI tests

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/wordpress-network#5]
@greg-1-anderson, can you give me write access here too? I'd like to set up the same tests I did in the main WordPress repo: https://github.com/pantheon-systems/pantheon-wordpress-upstream-tests/issues/1

**Comment by greg-1-anderson** [comment]
Done

**Comment by stevector** [comment]
Thanks, I'm going to leave this issue open as a reminder to do the task (later today)

**Comment by stevector** [comment]
Circle is now on
